version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  vite-app:
    build:
      context: .
      dockerfile: docker/vite/Dockerfile
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app
      - vite-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge