version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - app-network

  vite-app:
    build:
      context: .
      dockerfile: docker/vite/Dockerfile
    volumes:
      - /app/node_modules
      - ./frontend:/app/frontend
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app
      - vite-app
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: jm
      POSTGRES_PASSWORD: jm1234
      POSTGRES_DB: jm_decoracao
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge