server {
    listen 80;

    # serve arquivos estáticos do frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    # proxy para backend - localhost:8080/api vai para o serviço "app" na porta 3000
    location /api {
        proxy_pass http://app:3000;
    }
}
